POST http://localhost:3000/api/cursos/programacion HTTP/1.1
Content-Type: application/json

{
    "id": 4,
    "titulo": "Aprender Nodejs",
    "lenguaje": "javascript",
    "vistas": 19000,
    "nivel": "intermedio"
}

###

PUT http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "titulo": "python intemedio con proyecto",
    "lenguaje": "python",
    "vistas": 199999,
    "nivel": "intermedio"
}
###

PATCH http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "titulo": "python avanzada",
    "vistas": 77777
}
###

DELETE http://localhost:3000/api/cursos/programacion/1 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/cursos/programacion HTTP/1.1
Content-Type: application/json
